version: '3.8'

services:
  database:
    container_name: postgres
    image: postgres:15.2
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - DB_NAME=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./data_db/:/var/lib/postgresql/data

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    stop_signal: SIGTERM
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./.env:/src/.env
      - ./migrations:/src/migrations
      - ./alembic.ini:/src/alembic.ini
    entrypoint: sh -c "sleep 10 && alembic upgrade head && uvicorn --host 0.0.0.0 main:app"
    depends_on:
      - database
