"""Create tables

Revision ID: f9da76e6d0d4
Revises: 
Create Date: 2024-11-16 10:18:52.859421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9da76e6d0d4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AccountUser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deposit', sa.DECIMAL(), nullable=True),
    sa.Column('wallet_uuid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_AccountUser_id'), 'AccountUser', ['id'], unique=False)
    op.create_index(op.f('ix_AccountUser_wallet_uuid'), 'AccountUser', ['wallet_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_AccountUser_wallet_uuid'), table_name='AccountUser')
    op.drop_index(op.f('ix_AccountUser_id'), table_name='AccountUser')
    op.drop_table('AccountUser')
    # ### end Alembic commands ###
